name: Expo Publish

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - name: Set up expo
      uses: expo/expo-github-actions@v5
      with: 
        expo-version: 3.x
        expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      
    - name: Install dependencies
      run: yarn
    
    - name: Expo Publish
      run: expo publish
  


    